services:
  mysql-app-container:
    build: ./mysql/
    container_name: mysql-app-container
    restart: always
    ports:
      - "3333:3306"  # Expose the MySQL port
    environment:
      MYSQL_ROOT_PASSWORD: '1234'
      MYSQL_DATABASE: 'landarea'
  web-ui:
    build: ./frontend
    ports: 
     - "3000:3000"
    volumes:
    - ./frontend/:/app
    restart: unless-stopped
    container_name: web-ui
    stdin_open: true
    tty: true
    depends_on:
      - pythonapp
  pythonapp:
    build: ./backend/
    restart: always
    container_name: pythonapp
    ports:
      - "80:5000"  # Expose the port your Python app listens on
    depends_on:
      - mysql-app-container