version: '3.8'

services:
  mysql-app-container:
    build: ./mysql/
    container_name: mysql-app-container
    restart: always
    ports:
      - "3333:3306"  # Expose the MySQL port
    environment:
      MYSQL_ROOT_PASSWORD: '1234'
      MYSQL_DATABASE: 'landarea'

  web-ui:
    build: ./frontend
    container_name: web-ui
    ports: 
      - "80:3000"
    volumes:
      - ./frontend/:/app
    restart: unless-stopped
    stdin_open: true
    tty: true
    depends_on:
      - pythonapp

  pythonapp:
    build: ./backend/
    container_name: pythonapp
    restart: always
    ports:
      - "5000:5000"  # Expose the port your Python app listens on
    depends_on:
      - mysql-app-container
